### PR TITLE
chore: request permissions for custom hosts (resolve #209)

### LINKED ISSUE #209: Allow to request permissions for custom hosts
#130 introduced the ability to configure custom API URLs, so the plugin can be used with self-hosted WakaTime alternative like [Wakapi](https://github.com/muety/wakapi) as well. However, to actually use this, people would have to build their own version of the browser add-on with `host_permissions` configured to permit requests to their own instances.

I propose to ...
* ... allow `wakapi.dev` by default.
* ... to request for optional host permissions when custom URL is configured (see [here](https://stackoverflow.com/questions/71913706/is-it-possible-for-a-webextension-addon-to-request-permission-for-a-specific-web), [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions/request#examples) and [here](https://github.com/SettingDust/obsidian-web-clipper/blob/main/src/manifest.json)).

### PR DESCRIPTION
**Pull request by muety**
Resolve #209

### CODE REVIEW

**Comment by gandarez** [comment]
@jvelezpo would you like to review it?

**Comment by muety** [comment]
Didn't get that error 🤔 How could I reproduce it?

I'd appreciate some help! I'm not too experienced with web extensions.

Btw., for Wakapi you'll have to put `https://wakapi.dev/api/compat/wakatime/v1`.

**Comment by jvelezpo** [comment]
https://github.com/wakatime/browser-wakatime/pull/222#issuecomment-1632547962

**Comment by jvelezpo** [comment]
Closing, merged this other PR instead 
 https://github.com/wakatime/browser-wakatime/pull/222

**Comment by muety** [comment]
Awesome, thanks! When will the next release be published?

**Pull request closed without merging**
